push to stable
AFLplusplus/AFLplusplus pull request #1023
Opened 2021-07-15 07:42 UTC by vanhauser-thc

IMHO we should make a release now before the documentation rewrite project is making changes, as until it ends I feel there could be too many inconsistencies.

So we should do the release  early next week.

WDYT?

2021-07-15 07:45 UTC, vanhauser-thc commented
Is someone able to resolve the conflict?
I dont understand why we have a conflict every time we push.
And I am clueless how to resolve them if they cant be resolved via the web UI :-( (I don't undestand the hints github gives on how to do this via the cmdline ...)

2021-07-15 10:26 UTC, domenukk approved these changes

2021-07-15 10:26 UTC, domenukk commented on docs/Changelog.md
> -    - performance fix when cmplog was used
Has this been scrapped?

2021-07-15 10:26 UTC, domenukk commented on docs/perf_tips.md
> +Consider setting low values for -m and -t.
In backticks?

2021-07-15 10:30 UTC, vanhauser-thc commented on docs/Changelog.md
> -    - performance fix when cmplog was used
error on my side to add this

2021-07-15 10:43 UTC, vanhauser-thc commented on docs/perf_tips.md
> +Consider setting low values for -m and -t.
done

2021-07-15 10:52 UTC, vanhauser-thc commented on src/afl-fuzz-mutators.c
> +  while (afl->stage_cur <= afl->stage_max) {
can someone have a look here? from our documentation we tell to return fir trim_post 1 if more trims can be done, resetting stage_max to 1, but stage_cur is 1 after the first loop ... what do?

2021-07-15 12:19 UTC, WorksButNotTested commented
> @WorksButNotTested by trying to resolve merge conflicts, this file appeared from stable. Is it supposed to be there, or not?
> Sorry :)

This python script has been replaced with a shell script in the `dev` branch to reduce FRIDA mode's build dependencies.

2021-07-15 22:46 UTC, hexcoder- approved these changes

2021-07-15 22:50 UTC, hexcoder- commented
Good planning to push now to stable! Makes our lives probably easier later.

2021-07-17 04:21 UTC, WorksButNotTested requested changes
Awesome. Thanks for sorting that.

2021-07-19 08:31 UTC, merged