push to stable
AFLplusplus/AFLplusplus pull request #1236
Opened 2021-12-29 17:25 UTC by vanhauser-thc

nyx, frida, fixes, ...

2022-01-03 06:27 UTC, hexcoder- requested changes
most replacements in src/afl-fuzz-redqueen.c were outside of comments.
Please revert them, they changed behaviour.

2022-01-03 06:27 UTC, hexcoder- commented on src/afl-fuzz-redqueen.c
>        if (*status != 1) {
Probably wrong!!

2022-01-03 06:27 UTC, hexcoder- commented on src/afl-fuzz-redqueen.c
dito

2022-01-03 06:27 UTC, hexcoder- commented on src/afl-fuzz-redqueen.c
dito

2022-01-03 06:27 UTC, hexcoder- commented on src/afl-fuzz-redqueen.c
dito

2022-01-03 08:15 UTC, vanhauser-thc commented on src/afl-fuzz-redqueen.c
yes that was nonsense, thank you!

2022-01-03 10:36 UTC, hexcoder- approved these changes

2022-01-03 10:36 UTC, hexcoder- commented on test/test-llvm.sh
>      ../afl-clang-fast -o test-dlopen.plain test-dlopen.c ${LIBS} > /dev/null 2>&1
I think `:` (aka `true`) is needed because otherwise there is no command after `&&`.

2022-01-03 10:36 UTC, hexcoder- commented on nyx_mode/custom_harness/example.c
> +	}
German error messages might be unexpected to our users...

2022-01-03 10:36 UTC, hexcoder- commented on docs/INSTALL.md
> +* binary-only: everything for binary-only fuzzing: frida_mode, qemu_mode,
how about nyx_mode here?

2022-01-03 10:36 UTC, hexcoder- commented on include/envs.h
> +    "AFL_SKIP_OSSFUZZ",
`AFL_SKIP_OSSFUZZ` is not documented in `docs/env_variables.md`.

Also `AFL_NO_SNAPSHOT` in `docs/env_variables.md` seems to be outdated, at least I never got lkm snapshots working and they are currently not maintained...

2022-01-03 10:36 UTC, hexcoder- commented on instrumentation/afl-compiler-rt.o.c
> +    if (!getenv("AFL_IGNORE_PROBLEMS")) {
is this env. var. documented?

2022-01-03 14:38 UTC, vanhauser-thc commented on test/test-llvm.sh
>      ../afl-clang-fast -o test-dlopen.plain test-dlopen.c ${LIBS} > /dev/null 2>&1
nope not needed

2022-01-03 14:55 UTC, vanhauser-thc commented on include/envs.h
> +    "AFL_SKIP_OSSFUZZ",
doesnt need to be document it is oss-fuzz internal only

2022-01-03 14:57 UTC, vanhauser-thc commented on nyx_mode/custom_harness/example.c
> +	}
right

2022-01-03 15:25 UTC, vanhauser-thc commented on docs/INSTALL.md
> +* binary-only: everything for binary-only fuzzing: frida_mode, qemu_mode,
yes

2022-01-03 15:26 UTC, vanhauser-thc commented on instrumentation/afl-compiler-rt.o.c
> +    if (!getenv("AFL_IGNORE_PROBLEMS")) {
a grep would have told you ... "yes" :)

2022-01-07 12:13 UTC, vanhauser-thc commented
there is another nyx patch comming soon, we should wait for this until merging
@schumilo

2022-01-11 11:20 UTC, merged